#import "@preview/glossarium:0.5.1": gls, glspl

== Grammar Models <outlook.grammar.sec>
While the current #gls("GEC") model for Faroese demonstrates promising performance, it remains limited in several key areas. One primary constraint lies in its token-based correction strategy, which restricts edits to surface-level replacements without considering deeper syntactic relationships. In contrast, dependency-based approaches, which utilize a syntactic parse of the sentence, could enable more structurally aware corrections, especially for complex grammatical constructions or long-distance agreement errors. \ \
Further improvements in performance and linguistic accuracy could be achieved by incorporating richer grammatical analysis tools into the pipeline. At present, the supporting infrastructure for Faroese #gls("NLP") is still relatively sparse. The current spaCy setup includes only a POS tagger and a morphologizer, both trained on top of a multilingual transformer. However, a full spaCy pipeline, including components like a dependency parser, named entity recognizer, lemmatizer, and sentence segmenter would offer a much more robust linguistic backbone for grammar correction.\ \
Such components could provide the model with fine-grained linguistic signals that go beyond token classification. For example, a syntactic dependency tree could help the model distinguish between subjects and objects, improving its handling of agreement, case, and word order. Likewise, reliable sentence segmentation and lemmatization would enhance the model's ability to make consistent and contextually appropriate edits. \ \
Looking ahead, the development of these tools, either by training them directly for Faroese or by adapting them through multilingual transfer learning, could significantly boost the quality and interpretability of grammar correction systems. Moreover, such infrastructure would not only benefit #gls("GEC"), but also support a wide range of downstream applications.


== Spelling Models <outlook.spelling.sec>
The current spelling correction model for Faroese shows encouraging early results, but it still faces notable challenges. One of the main limitations is that it tends to introduce too many false corrections, suggesting that the model is not yet precise enough in distinguishing between genuine errors and valid but less common word forms. \ \
Another key issue lies in the evaluation process. The current test set contains too few actual spelling errors, which makes it difficult to reliably assess the model's effectiveness. This data imbalance skews evaluation metrics and may give a misleading impression of model performance. Without a test set that reflects the true frequency and variety of real-world spelling mistakes, it remains challenging to track progress accurately.\ \
Looking forward constructing or curating a more representative evaluation dataset, either by introducing synthetic errors or collecting user-generated data, would allow for more meaningful performance assessment. \ \
Importantly, an improved test set would not only provide a more accurate measure of current performance but also help guide further development of the model. It would offer clearer insights into whether the model architecture is sufficient or if additional tools might be needed to better handle the complexities of Faroese spelling. At present, the limited nature of the test set makes it difficult to draw such conclusions with confidence.
