#let glossary = (
  (key: "AI", short: "AI", long: "Artificial Intelligence"),
  (key: "BEND", short: "Bendingargrunnurin", long: "The Inflection Database"),
  (key: "BART", short: "BART", long: "Bidirectional and Auto-Regressive Transformers"),
  (key: "BERT", short: "BERT", long: "Bidirectional Encoder Representations from Transformers"),
  (key: "BITEXT", short: "bitext", long: "billingual text"),
  (key: "C4", short: "C4", long: "Colossal Clean Crawled Corpus"),
  (key: "CNN", short: "CNN", long: "Convolutional Neural Network"),
  (key: "DAG", short: "DAG", long: "Directed Acyclic Graph"),
  (key: "DOC", short: "Doc", long: "spaCy Doc"),
  (key: "DOCB", short: "DocBin", long: "spaCy DocBin"),
  (key: "ðb", short: "Eth - byttet ð", long: "Eth - swapped ð"),
  (key: "ðm", short: "Eth - mangler ð", long: "Eth - missing ð"),
  (key: "ðt", short: "Eth - tilføjet ð", long: "Eth - added ð"),
  (key: "ESTV", short: "ESTV", long: "An Extended Sequence Tagging Vocabulary for Grammatical Error Correction", ),
  (key: "FN", short: "FN", long: "False Negative"),
  (key: "FFN", short: "FFN", long: "Feed Forward Neural Network"),
  (key: "FO_OB", short: "Føroysk orðabók", long: "Faroese Dictionary"),
  (key: "FP", short: "FP", long: "False Positive"),
  (key: "FRO", short: "Fróðskaparrit", long: "Faroese Scientific Journal"),
  (key: "FROB", short: "Fróðskapur", long: "Faroe University Press"),
  (key: "GEC", short: "GEC", long: "Grammatical Error Correction"),
  (key: "GECTOR", short: "GECToR", long: "Grammatical Error Correction: Tag, Not Rewrite"),
  (key: "GELU", short: "GeLU", long: "Gaussian Error Linear Unit"),
  (key: "GPT", short: "GPT", long: "Generative Pre-trained Transformer"),
  (key: "GT", short: "GT", long: "Ground Truth"),
  (key: "HMM", short: "HMM", long: "Hidden Markov Model"),
  (key: "IRP", short: "IRP", long: "Iterative Refinement Pipeline"),
  (key: "JSON", short: "JSON", long: "JavaScript Object Notation"),
  (key: "JSONL", short: "JSONL", long: "JSON Lines"),
  (key: "LAS", short: "LAS", long: "Labeled Attachment Score"),
  (key: "LM", short: "LM", long: "Language Model"),
  (key: "LSTM", short: "LSTM", long: "Long Short-Term Memory"),
  (key: "MAL", short: "Málráðið", long: "The Faroese Language Council"),
  (key: "MBART", short: "mBART", long: "Multilingual Bidirectional and Auto-Regressive Transformers"),
  (key: "MBERT", short: "mBERT", long: "Multilingual Bidirectional Encoder Representations from Transformers"),
  (key: "MLM", short: "MLM", long: "Masked Language Modeling"),
  (key: "MC4", short: "mC4", long: "Multilingual Colossal Clean Crawled Corpus"),
  (key: "MLP", short: "MLP", long: "Multilayer Perceptron"),
  (key: "MORPH", short: "MORPH", long: "Morphologizer"),
  (key: "MT5", short: "mT5", long: "Multilingual Text-to-Text Transfer Transformer"),
  (key: "MTD", short: "MTD", long: "The Faroese Centre for Language Technology"),
  (key: "NLLB", short: "NLLB", long: "No Language Left Behind"),
  (key: "NLP", short: "NLP", long: "Natural Language Processing"),
  (key: "NUCLE", short: "NUCLE", long: "Nonnative Corpus of Learner English"),
  (key: "NER", short: "NER", long: "Named Entity Recognition"),
  (key: "PIE", short: "PIE", long: "Parallel Iterative Edit"),
  (key: "POS", short: "POS", long: "Part-of-Speech"),
  (key: "REP", short: "REP", long: "Replacement Pattern"),
  (key: "RÆTT", short: "Rættstavarin", long: "The Spell Checker"),
  (key: "RELU", short: "ReLU", long: "Rectified Linear Unit"),
  (key: "RNN", short: "RNN", long: "Recurrent Neural Network"),
  (key: "S2S", short: "Seq2Seq", long: "Sequence-to-Sequence"),
  (key: "SETUR", short: "SETUR", long: "The University of the Faroe Islands"),
  (key: "SOTA", short: "SOTA", long: "State-of-the-Art"),
  (key: "SNI", short: "SNI", long: "Semantic Textual Similarity"),
  (key: "SPEC", short: "SPEC", long: "Spelling Error Correction"),
  (key: "T5", short: "T5", long: "Text-to-Text Transfer Transformer"),
  (key: "TN", short: "TN", long: "True Negative"),
  (key: "TP", short: "TP", long: "True Positive"),
  (key: "UAS", short: "UAS", long: "Unlabeled Attachment Score"),
  (key: "UD", short: "UD", long: "Universal Dependencies"),
  (key: "WER", short: "WER", long: "Word Error Rate"),
  (key: "XLMR", short: "XLM-R", long: "Cross-lingual Language Model - RoBERTa"),
)