#let glossary = (
  (key: "NLP", short: "NLP", long: "Natural Language Processing"),
  (key: "GEC", short: "GEC", long: "Grammatical Error Correction"),
  (key: "RNN", short: "RNN", long: "Recurrent Neural Network"),
  (key: "LSTM", short: "LSTM", long: "Long Short-Term Memory"),
  (key: "MLP", short: "MLP", long: "Multilayer Perceptron"),
  (key: "s2s", short: "Seq2Seq", long: "Sequence-to-Sequence"),
  (key: "PIE", short: "PIE", long: "Parallel Iterative Edit"),
  (key: "ESTV", short: "ESTV", long: "An Extended Sequence Tagging Vocabulary for Grammatical Error Correction", ),
  (key: "LM", short: "LM", long: "Language Model"),
  (key: "SOTA", short: "SOTA", long: "State-of-the-Art"),
  (key: "POS", short: "POS", long: "Part-of-Speech"),
  (key: "TP", short: "TP", long: "True Positive"),
  (key: "FP", short: "FP", long: "False Positive"),
  (key: "TN", short: "TN", long: "True Negative"),
  (key: "FN", short: "FN", long: "False Negative"),
  (key: "AI", short: "AI", long: "Artificial Intelligence"),
  (key: "SPEC", short: "SPEC", long: "Spelling Error Correction"),
  (key: "HMM", short: "HMM", long: "Hidden Markov Model"),
  (key: "WER", short: "WER", long: "Word Error Rate"),
  (key: "GT", short: "GT", long: "Ground Truth"),
  (key: "IRP", short: "IRP", long: "Iterative Refinement Pipeline"),
  (key: "BERT", short: "BERT", long: "Bidirectional Encoder Representations from Transformers"),
  (key: "T5", short: "T5", long: "Text-to-Text Transfer Transformer"),
  (key: "MORPH", short: "MORPH", long: "Morphologizer"),
  (key: "MTD", short: "MTD", long: "The Centre for Language Technology"),
  (key: "SETUR", short: "SETUR", long: "The Faroese Language Council"),
)