#import "@preview/glossarium:0.5.1": gls, glspl
#import "../utils.typ": flex-caption, customRound

= Conclusion <conclusion.sec>
This thesis set out to explore the feasibility of developing foundational language models for ultra-low resource languages, using Faroese as a case study. In doing so, it addressed a pressing gap in #gls("NLP") research: the scarcity of tools and annotated resources for languages with limited digital footprints. By focusing on #gls("GEC") as a central task, and building supporting components such as a #gls("POS") tagger, morphologizer, lemmatizer, and dependency parser, this work provides a grounded assessment of what is realistically achievable in such resource-constrained settings. \ \
The results demonstrate that certain components, most notably the #gls("POS") tagger and morphologizer trained using the spaCy framework, are viable with the currently available Faroese Universal Dependencies datasets. These tools deliver acceptable performance and offer a solid linguistic backbone for future grammatical modeling efforts. \ \
However, other components present greater challenges. The initial #gls("GEC") model faced significant limitations due to the quality of the training data and an overly simplistic corruption process, which prone to introducing errors rather than correcting them. Subsequent improvements to the corruption mechanism and the development of a second #gls("GEC") model suggest more promising directions, although the model is still in early stages and requires further evaluation. \ \
Conversely, both the lemmatizer and the dependency parser proved inadequate under current conditions. Their poor performance highlights a clear need for additional annotated data. These results reinforce the idea that, while transfer learning and lightweight architectures can help, some foundational level of annotated linguistic data remains essential.\ \
Finally, the exploration of a spelling model offers a useful complement to #gls("GEC"), addressing surface-level errors that frequently co-occur with deeper grammatical issues. Although not yet fully integrated, this line of work shows potential for improving overall correction quality in real-world scenarios. \ \
In sum, this thesis illustrates both the opportunities and constraints involved in developing #gls("NLP") systems for ultra-low resource languages. It provides practical insights into data needs, tool performance, and workflow design, contributions that can inform future efforts not only in Faroese, but across the broader landscape of digitally marginalized languages.