#import "@preview/glossarium:0.5.1": gls, glspl
#import "../../utils.typ": flex-caption, customRound

== Categorizing Error types <categorizing_errors.sec>
The categorizing of errors is an essential part of the #gls("GEC") process, as it allows for a more structured approach to error correction. In this section, we will categorize the errors that are introduced by the models, and how they are handled in the pipeline. The errors are categorized into three main categories: *Spelling*, *Grammar* and *Punctuation*. The *Spelling* category includes errors that are related to spelling, such as missing or added letters, swapped letters, and incorrect capitalization. The *Grammar* category includes errors that are related to grammar, such as incorrect verb forms, incorrect noun forms, and incorrect word order. The *Punctuation* category includes errors that are related to punctuation, such as missing or added punctuation marks, and incorrect punctuation marks. Each of these categories is further divided into subcategories, which are described in the following sections.

=== Spelling Errors
Spelling error types will have a name that starts with either *Spelling mistake* or #gls("REP"). In general *Spelling mistake* refers to a word that is misspelled, while #gls("REP") refers to a pattern that is replaced with an error, for example *Rep "rsk" and "rk"* refers to the pattern "rsk" being replaced with "rk" and vice versa. Any #gls("REP") where there is an *and* between the two words, refers to a two way relation, where both patterns can be replaced with each other, if there is an *with* between the two words, it refers to a one way relation, where the first pattern is replaced with the second pattern, but not vice versa. In addition to this, there are *Double consonant* and *Vowel confusion*. *Double consonant* refers to any mistake where a consonant should be doubled, but isn't or vice versa, while *Vowel confusion* refers to a mistake where a vowel is confused with another vowel, for example "a" and "æ" or "i" and "y". Other error types that don't fall into the above categories, will have a name that describes the error type, such as *Capital initial letter*.

=== Grammar Errors
Grammar error types will often have a name that describes the word class that is being corrected, for example for an inflexion error, it will have the name of the wordclass the word belongs to, such as *Adjectives*, *Nouns* or *Verbs*. A broad error type like *Verbs* can also have a more specific error type, such as *Verb Tense Agreement* or *Verb Subject agreement*, this indicates that if there is an overlap where the error type can fall under either *Verbs* or *Verb Tense Agreement*, then the more specific error type will take priority be used. In addition to this, there are some error types where it says *added*, *missing*, *important* or *redundant*. *Added* and *Redundant* refer to a character or a word that is added to the sentence incorrectly or is redundant, while *Missing* refers to a character that is missing from the sentence, and *Important* refers to a word that is important for the sentence, but is missing. Other error types that dont fall into the above categories, will have a name that describes the error type, such as *Nomen Agensis*.

=== Punctuation Errors
Punctuation errors are either called the name of the punctuation mark that is being corrected, such as *Comma* or *Period*, or the are preceded by *Punctuation -* if they are less common, such as *Punctuation - exclaimation mark* or *Punctuation - missing space*. In the same way as with the grammar errors, an error type can have a more specific error type, such as *Comma - listing*, where the listing error will take priority over the general *Comma* error type.